version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1884:1884"  # Port MQTT
      - "9001:9001"  # Port WebSocket (opsional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - mqtt-broker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:5173"  # Port Vite
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app  # Volume untuk sinkronisasi kode
      - node_modules:/app/node_modules

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"  # Port HTTP untuk akses API InfluxDB
    volumes:
      - influxdb-data:/var/lib/influxdb2  # Data InfluxDB akan disimpan di volume ini
    environment:
      - INFLUXDB_DB=sensordata
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_HTTP_AUTH_ENABLED=true

volumes:
  node_modules:
  influxdb-data: